# Generated by Django 3.1.3 on 2021-02-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_food_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
