# Generated by Django 3.1.3 on 2021-02-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0008_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
