# Generated by Django 3.1.3 on 2021-01-31 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='date published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
