# Generated by Django 3.1.3 on 2021-01-31 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210130_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='date published',
            new_name='pub_date',
        ),
    ]
